_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
  resource: "@UserBundle/Controller/"
  type:     annotation
  prefix:   /

app:
  resource: "@AppBundle/Controller/"
  type:     annotation
